In [1]:
import altair as alt
import pandas as pd

# Load the  dataset
df = pd.read_csv('tmdb_5000_movies.csv')

In [2]:
#See genres
genres = set()
for genre_list in df['genres']:
    genre_dicts = eval(genre_list)
    for genre_dict in genre_dicts:
        genres.add(genre_dict['name'])

genres

{'Action',
 'Adventure',
 'Animation',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Family',
 'Fantasy',
 'Foreign',
 'History',
 'Horror',
 'Music',
 'Mystery',
 'Romance',
 'Science Fiction',
 'TV Movie',
 'Thriller',
 'War',
 'Western'}

In [3]:
#see data type
df.dtypes
# The dataset has the following features:-

# budget - The budget in which the movie was made.
# genre - The genre of the movie, Action, Comedy ,Thriller etc.
# homepage - A link to the homepage of the movie.
# id - This is infact the movie_id as in the first dataset.
# keywords - The keywords or tags related to the movie.
# original_language - The language in which the movie was made.
# original_title - The title of the movie before translation or adaptation.
# overview - A brief description of the movie.
# popularity - A numeric quantity specifying the movie popularity.
# production_companies - The production house of the movie.
# production_countries - The country in which it was produced.
# release_date - The date on which it was released.
# revenue - The worldwide revenue generated by the movie.
# runtime - The running time of the movie in minutes.
# status - "Released" or "Rumored".
# tagline - Movie's tagline.
# title - Title of the movie.
# vote_average - average ratings the movie recieved.
# vote_count - the count of votes recieved.

budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
dtype: object

In [4]:
import json

# assuming 'df' is the DataFrame containing the 'genres' column
# genre_names = df['genres'].apply(lambda x: [d['name'] for d in json.loads(x)])
# genre_names 
# # options=list(iris['species'].unique()
# list(df['spoken_languages'].unique())

             
# genres_selector = alt.binding_select(options:'genre_names')
# genres_dropdown = alt.selection_single(fields=['genres'], bind=experience_selector, name='GENERS: ') 
df['genres'] = df['genres'].apply(json.loads)

# Extract genre names and create a new column
df['genre_names'] = df['genres'].apply(lambda x: [genre['name'] for genre in x])
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,genre_names
0,237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"[Action, Adventure, Fantasy, Science Fiction]"
1,300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"[Adventure, Fantasy, Action]"
2,245000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,"[Action, Adventure, Crime]"
3,250000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,"[Action, Crime, Drama, Thriller]"
4,260000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,"[Action, Adventure, Science Fiction]"

In [5]:
df['genres']

0       [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
1       [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2       [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
3       [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
4       [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
                              ...
4798    [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
4799    [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
4800    [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4801                                                   []
4802                  [{'id': 99, 'name': 'Documentary'}]
Name: genres, Length: 4803, dtype: object

In [6]:
# df['genres'] = df['genres'].apply(json.loads)

# Extract the genre names and create a new column
pd.set_option('display.max_columns', None)  #set to show max rows

df['genre_names'] = df['genres'].apply(lambda x: [genre['name'] for genre in x])

df_exploded = df.explode('genre_names')

# Print the first five rows of the new DataFrame
print(df_exploded.head(100))
df_exploded.shape

       budget                                             genres  \
0   237000000  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
0   237000000  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
0   237000000  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
0   237000000  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
1   300000000  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
..        ...                                                ...
30  200000000  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
31  200000000  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
31  200000000  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
31  200000000  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
32  200000000  [{'id': 10751, 'name': 'Family'}, {'id': 14, '...

                                           homepage     id  \
0                       http://www.avatarmovie.com/  19995
0                       http://www.avatarmovie.com/  19995
0                       http://www.avatarmovie.com/  19995
0                       http://www.avatarmovie.com/  19995
1      http://disney.go.com/disneypictures/pirates/    285
..                                              ...    ...
30  http://www.sonypictures.com/movies/spider-man2/    558
31                       http://marvel.com/ironman3  68721
31                       http://marvel.com/ironman3  68721
31                       http://marvel.com/ironman3  68721
32                 http://disney.go.com/wonderland/  12155

                                             keywords original_language  \
0   [{"id": 1463, "name": "culture clash"}, {"id":...                en
0   [{"id": 1463, "name": "culture clash"}, {"id":...                en
0   [{"id": 1463, "name": "culture clash"}, {"id":...                en
0   [{"id": 1463, "name": "culture clash"}, {"id":...                en
1   [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en
..                                                ...               ...
30  [{"id": 851, "name": "dual identity"}, {"id": ...                en
31  [{"id": 949, "name": "terrorist"}, {"id": 5597...                en
31  [{"id": 949, "name": "terrorist"}, {"id": 5597...                en
31  [{"id": 949, "name": "terrorist"}, {"id": 5597...                en
32  [{"id": 818, "name": "based on novel"}, {"id":...                en

                              original_title  \
0                                     Avatar
0                                     Avatar
0                                     Avatar
0                                     Avatar
1   Pirates of the Caribbean: At World's End
..                                       ...
30                              Spider-Man 2
31                                Iron Man 3
31                                Iron Man 3
31                                Iron Man 3
32                       Alice in Wonderland

                                             overview  popularity  \
0   In the 22nd century, a paraplegic Marine is di...  150.437577
0   In the 22nd century, a paraplegic Marine is di...  150.437577
0   In the 22nd century, a paraplegic Marine is di...  150.437577
0   In the 22nd century, a paraplegic Marine is di...  150.437577
1   Captain Barbossa, long believed to be dead, ha...  139.082615
..                                                ...         ...
30  Peter Parker is going through a major identity...   35.149586
31  When Tony Stark's world is torn apart by a for...   77.682080
31  When Tony Stark's world is torn apart by a for...   77.682080
31  When Tony Stark's world is torn apart by a for...   77.682080
32  Alice, an unpretentious and individual 19-year...   78.530105

                                 production_companies  \
0   [{"name": "Ingenious Film Partners", "id": 289...
0   [{"name": "Ingenious Film Partners", "id": 289...
0   [{"name": "Ingenious Film Partners", "id": 289...
0   [{"name": "Ingenious Film Partners", "id": 289...
1   [{"name": "Walt Disney Pictures", "id": 2}, {"...
..                                                ...
30  [{"name": "Columbia Pictures", "id": 5}, {"nam...
31            [{"name": "Marvel Studios", "id": 420}]
31            [{"name": "Marvel Studios", "id": 420}]
31            [{"name": "Marvel Studios", "id": 420}]
32  [{"name": "Walt Disney Pictures", "id": 2}, {"...

                                 production_countries release_date  \
0   [{"iso_3166_1": "US", "name": "United States o...   2009-12-10
0   [{"iso_3166_1": "US", "name": "United States o...   2009-12-10
0   [{"iso_3166_1": "US", "name": "United States o...   2009-12-10
0   [{"iso_3166_1": "US", "name": "United States o...   2009-12-10
1   [{"iso_3166_1": "US", "name": "United States o...   2007-05-19
..                                                ...          ...
30  [{"iso_3166_1": "US", "name": "United States o...   2004-06-25
31  [{"iso_3166_1": "CN", "name": "China"}, {"iso_...   2013-04-18
31  [{"iso_3166_1": "CN", "name": "China"}, {"iso_...   2013-04-18
31  [{"iso_3166_1": "CN", "name": "China"}, {"iso_...   2013-04-18
32  [{"iso_3166_1": "US", "name": "United States o...   2010-03-03

       revenue  runtime                                   spoken_languages  \
0   2787965087    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...
0   2787965087    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...
0   2787965087    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...
0   2787965087    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...
1    961000000    169.0           [{"iso_639_1": "en", "name": "English"}]
..         ...      ...                                                ...
30   783766341    127.0  [{"iso_639_1": "en", "name": "English"}, {"iso...
31  1215439994    130.0           [{"iso_639_1": "en", "name": "English"}]
31  1215439994    130.0           [{"iso_639_1": "en", "name": "English"}]
31  1215439994    130.0           [{"iso_639_1": "en", "name": "English"}]
32  1025491110    108.0           [{"iso_639_1": "en", "name": "English"}]

      status                                         tagline  \
0   Released                     Enter the World of Pandora.
0   Released                     Enter the World of Pandora.
0   Released                     Enter the World of Pandora.
0   Released                     Enter the World of Pandora.
1   Released  At the end of the world, the adventure begins.
..       ...                                             ...
30  Released                    There's a hero in all of us.
31  Released             Unleash the power behind the armor.
31  Released             Unleash the power behind the armor.
31  Released             Unleash the power behind the armor.
32  Released        You're invited to a very important date.

                                       title  vote_average  vote_count  \
0                                     Avatar           7.2       11800
0                                     Avatar           7.2       11800
0                                     Avatar           7.2       11800
0                                     Avatar           7.2       11800
1   Pirates of the Caribbean: At World's End           6.9        4500
..                                       ...           ...         ...
30                              Spider-Man 2           6.7        4321
31                                Iron Man 3           6.8        8806
31                                Iron Man 3           6.8        8806
31                                Iron Man 3           6.8        8806
32                       Alice in Wonderland           6.4        4645

        genre_names
0            Action
0         Adventure
0           Fantasy
0   Science Fiction
1         Adventure
..              ...
30          Fantasy
31           Action
31        Adventure
31  Science Fiction
32           Family

[100 rows x 21 columns]

(12188, 21)

In [7]:
df['release_date']

0       2009-12-10
1       2007-05-19
2       2015-10-26
3       2012-07-16
4       2012-03-07
           ...
4798    1992-09-04
4799    2011-12-26
4800    2013-10-13
4801    2012-05-03
4802    2005-08-05
Name: release_date, Length: 4803, dtype: object

In [9]:

alt.data_transformers.enable('default', max_rows=None)#change max show restrict(may lead to collapse)
brush = alt.selection_interval(
    encodings=['x'] # limit selection to x-axis (year) values
)

# dynamic query histogram
#This is the first gram to show the year and movie genres on that year
#设计1：考虑到1980前的电影发行量不多，所以时间跨度展示了1980-2016年
#设计2： 图1为柱状图，可以很好地比较出各年份发行的电影的genre的总数量
#设计3：选中图1时，图2的非联动部分会显示出更淡的颜色，这有利于筛选出与图1相关的内容
year_count = alt.Chart(df_exploded).mark_bar(clip=True,color = "#74c476").add_selection(
    brush
).encode(
    alt.X('year(release_date):T', title='movie types by movie release Year',scale=alt.Scale(domain=[1980,2017])),
    alt.Y('count():Q', title=None),

).properties(
    width=650,
    height=50,
)

#popular topic change
#设计4： 采用不同颜色标记电影的genre，让图表更为直观
#设计5： 鼠标放在某个圆圈上时可显示电影的相关信息（主题、预算、收入、流行度、评分），便于查找和信息之间的比对
#设计6： 图二设置了合适的透明度，故可以通过颜色深浅来判断某个genre大致都是什么样的流行度（这句话组织得不好，我不知道怎么表达）
popularity = alt.Chart(df_exploded).mark_circle().encode(
    x='genre_names:N',
    y='popularity:Q',
    size=alt.Size('vote_average:Q', scale=alt.Scale(range=[0,500])),
    color = alt.Color('genre_names:N', scale=alt.Scale(scheme='category20c')),
    tooltip=['original_title:N','budget','revenue','popularity','vote_average'],
    opacity=alt.condition(brush, alt.value(0.4), alt.value(0.05)),
#     shape = alt.Shape('genre_names'),
).properties(
    width=650,
    height=400,
)
#the relationship between budget and revenue
revenue = alt.Chart(df_exploded).mark_circle().encode(
    x='budget:Q',
    y='revenue:Q',
    color = alt.Color('genre_names:N', scale=alt.Scale(scheme='category20c')),
    size=alt.Size( scale=alt.Scale(range=[0,500])),
    tooltip=['original_title:N','genre_names:N','budget','revenue',],
    opacity=alt.condition(brush, alt.value(0.6), alt.value(0.05)),
#     shape = alt.Shape('genre_names'),
).properties(
    width=650,
    height=400,
)
chart = alt.vconcat(year_count, popularity,revenue).properties(
    spacing=10,

           )
chart.save("System A.html")